server:
  #程序端口号
  port: 8080
spring:
  application:
    #应用名称
    name: nacos-consumer-sample
  cloud:
    nacos:
      discovery:
        #nacos地址
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        #公开所有节点
        include: '*'